runtime: python39

env_variables:
  GOOGLE_CLOUD_BUCKET: "cbms_storage"
  GOOGLE_APPLICATION_CREDENTIALS: "service-account.json"
  PROJECT_ID: "cloud-based-media-storage"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

service: default