services:
  - type: web
    name: cbms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: singapore
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true