services:
  - type: web
    name: cbms
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/templates
      cp -r templates/* /opt/render/project/src/templates/
    startCommand: gunicorn app:app
    region: singapore
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STORAGE_BUCKET_NAME
        value: cbms-storage
      - key: STORAGE_LOCATION
        value: asia-south1
      - key: GOOGLE_CLOUD_PROJECT
        value: cloud-based-media-storage
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
    healthCheckPath: /
    autoDeploy: true